### ISSUE TITLE
Can you use this in a strategy world map?

### ISSUE THREAD

**Issue by MihailTrajkovski** [RoryDungan/HexTiles#6]
Hello,

Now I already saw in the other issue how you can put sprites and other game objects onto another tile with HexTileMap.QuantizePositionToHexGrid so that certainly answers one of my needs but I am creating a game like NEO Scavenger but any of the maps in the Civ games work pretty much in the same way. 
My question is would I be able to use this if my player needs to move with mouse/touch events? Would i need to add something myself in order for the hex grid map to work with a mouse/touch?
Is there an implementation for obstacles already?
And my last question: How easy would be to add special case models for the map i.e. if I want to create a coastline near bodies of water(This can be seen in the modern Civ games too)?

**Comment by RoryDungan** [comment]
Hey,

First I'll address your question about mouse/touch events. There is no input handling built into this library but the tool will generate colliders as well as visual meshes for all hex maps so you should be able to use [Physics.Raycast](https://docs.unity3d.com/ScriptReference/Physics.Raycast.html) and [Camera.ScreenPointToRay](https://docs.unity3d.com/ScriptReference/Camera.ScreenPointToRay.html), along with HexTileMap.QuantizePositionToHexGrid to find points on it. 

Creating more detailed meshes for areas like coastlines is a bit more complicated. Currently all meshes are generated procedurally via HexMeshGenerator, so if you want to have detailed sections for things like coastlines you'll have to either modify that to add a special case for the coastlines, do everything via the material (maybe via a geometry shader or something), or leave those bits empty and use a combination of manually placed meshes and generated hex meshes. 

If you're interested in modifying the library or using it as a basis for your own more advanced system, I'd recommend checking out Red Blob Games' [excellent guide](https://www.redblobgames.com/grids/hexagons/) on hexagonal grids or Catlike coding's [tutorial series](https://catlikecoding.com/unity/tutorials/hex-map/) on hex map generation.

Hope that helps!

**Comment by MihailTrajkovski** [comment]
Sorry it took me so long to respond,
Thank you for the resource I did know about the Catlike coding one but not the Red Blob one. I will try to use them together with your library.
