### ISSUE TITLE
Sides of Tiles appear as if they are shadowed regardless of lighting settings

### ISSUE THREAD

**Issue by Rienuaa** [RoryDungan/HexTiles#7]
I have a Hex Tiles map set up in my project running an out of the box URP shader for its rendering settings. Regardless of what material I place on the tiles themselves, the sides appear as if they are always shadowed. I have tried baking lighting with the global lighting settings and if I set a high enough intensity it's clear that the textures themselves are mapped correctly, they're just... very dark. At a global intensity of 1 they are too dark to see.
![sideways light](https://user-images.githubusercontent.com/5385208/95407915-510c5980-08ec-11eb-8c88-47097a67375a.PNG)

 If I turn off "Scene Lighting" the problem "fixes" itself, but inside the game that uses a "sun" (aka a directional light that rotates around the map and not baked skybox/environment lighting) the sides go back to being almost entirely matte black regardless. 

![no scene light](https://user-images.githubusercontent.com/5385208/95407912-5073c300-08ec-11eb-85a5-b2de8cd4e0ed.PNG)

Even if I turn off the directional light and used baked in lighting, it's still very very dark.
![shadow](https://user-images.githubusercontent.com/5385208/95407996-85801580-08ec-11eb-85c5-689edf28505f.PNG)

**Comment by RoryDungan** [comment]
Hi! I notice the capsule primitive in the first screenshot also looks quite dark so I suspect now this may be to do with your lighting setup, but if you can attach or link a sample project with a scene that has the issue I'd be happy to check it out. 

If there is an issue with the mesh that's being generated I think it's likely that the normals are not correct, so check with a tool that [visualises normals](https://www.reddit.com/r/Unity3D/comments/5m2uuw/draw_normals/) to see if they are correct. Currently the vertex normals are calculated in [HexChunk.GenerateMesh()](https://github.com/RoryDungan/HexTiles/blob/04fdfc97ac4401abae2f21efb5ab04645bc80e71/Assets/Code/HexTiles/HexChunk.cs#L176) by calling [Mesh.RecalculateNormals()](https://docs.unity3d.com/ScriptReference/Mesh.RecalculateNormals.html), but if that isn't calculating them correctly, that would be the place to look in the code to set up something different.

**Comment by RoryDungan** [comment]
Regarding the lighting, "Scene Lighting" is just a setting for how you view the scene in the editor so won't affect play mode. If all you want is to do is increase the ambient light level, the easiest way is to change Environment Lighting to a solid colour instead of Skybox and the set the colour of that. Check out the Unity docs on [Ambient light](https://docs.unity3d.com/Manual/lighting-ambient-light.html) and [the lighting window](https://docs.unity3d.com/Manual/lighting-window.html) for more info.

**Comment by Rienuaa** [comment]
Luckily, this has been resolved - the problem was that my directional light was too far away. After moving things in my scene and re-checking my lighting, everything looks perfect. Looks like this was entirely user error. Thank you!

![fixed](https://user-images.githubusercontent.com/5385208/95667381-34159780-0b33-11eb-8ff0-d7e519df8be4.PNG)
